AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CoDeezr

  CoDeezr music track search app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  CoDeezr:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      Description: API wrapper around Deezer API
      CorsConfiguration:
        MaxAge: 600
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
          - HEAD
          - PUT
          - PATCH
          - "*"
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"
        ExposeHeaders:
          - "*"

  SearchTracksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: search.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SearchTracks:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId:
              Ref: CoDeezr
            Path: /search
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - search.ts

  GetArtistFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: get-artist.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SearchTracks:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId:
              Ref: CoDeezr
            Path: /artist/{id}
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - get-artist.ts

  GetAlbumsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: get-albums.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SearchTracks:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId:
              Ref: CoDeezr
            Path: /artist/{id}/albums
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - get-albums.ts

  GetTopTracksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: get-top-tracks.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SearchTracks:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId:
              Ref: CoDeezr
            Path: /artist/{id}/top
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - get-top-tracks.ts
